#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSFGlasses
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GlassesDatabase")]
	public partial class LinqDatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBrandTBL(BrandTBL instance);
    partial void UpdateBrandTBL(BrandTBL instance);
    partial void DeleteBrandTBL(BrandTBL instance);
    partial void InsertUnloadReport(UnloadReport instance);
    partial void UpdateUnloadReport(UnloadReport instance);
    partial void DeleteUnloadReport(UnloadReport instance);
    partial void InsertCustomerTBL(CustomerTBL instance);
    partial void UpdateCustomerTBL(CustomerTBL instance);
    partial void DeleteCustomerTBL(CustomerTBL instance);
    partial void InsertDetailsTBL(DetailsTBL instance);
    partial void UpdateDetailsTBL(DetailsTBL instance);
    partial void DeleteDetailsTBL(DetailsTBL instance);
    partial void InsertGenderTBL(GenderTBL instance);
    partial void UpdateGenderTBL(GenderTBL instance);
    partial void DeleteGenderTBL(GenderTBL instance);
    partial void InsertHostTBL(HostTBL instance);
    partial void UpdateHostTBL(HostTBL instance);
    partial void DeleteHostTBL(HostTBL instance);
    partial void InsertKalaListTBL(KalaListTBL instance);
    partial void UpdateKalaListTBL(KalaListTBL instance);
    partial void DeleteKalaListTBL(KalaListTBL instance);
    partial void InsertKalaTBL(KalaTBL instance);
    partial void UpdateKalaTBL(KalaTBL instance);
    partial void DeleteKalaTBL(KalaTBL instance);
    partial void InsertMessageTBL(MessageTBL instance);
    partial void UpdateMessageTBL(MessageTBL instance);
    partial void DeleteMessageTBL(MessageTBL instance);
    partial void InsertOperaionsTBL(OperaionsTBL instance);
    partial void UpdateOperaionsTBL(OperaionsTBL instance);
    partial void DeleteOperaionsTBL(OperaionsTBL instance);
    partial void InsertorderedKalaTBL(orderedKalaTBL instance);
    partial void UpdateorderedKalaTBL(orderedKalaTBL instance);
    partial void DeleteorderedKalaTBL(orderedKalaTBL instance);
    partial void InsertRackTBL(RackTBL instance);
    partial void UpdateRackTBL(RackTBL instance);
    partial void DeleteRackTBL(RackTBL instance);
    partial void InsertReportTBL(ReportTBL instance);
    partial void UpdateReportTBL(ReportTBL instance);
    partial void DeleteReportTBL(ReportTBL instance);
    partial void InsertSetupTBL(SetupTBL instance);
    partial void UpdateSetupTBL(SetupTBL instance);
    partial void DeleteSetupTBL(SetupTBL instance);
    partial void InserttriggerTBL(triggerTBL instance);
    partial void UpdatetriggerTBL(triggerTBL instance);
    partial void DeletetriggerTBL(triggerTBL instance);
    partial void InsertUsersTBL(UsersTBL instance);
    partial void UpdateUsersTBL(UsersTBL instance);
    partial void DeleteUsersTBL(UsersTBL instance);
    #endregion
		
		public LinqDatabaseDataContext() : 
				base(global::SSFGlasses.Properties.Settings.Default.GlassesDatabaseConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BrandTBL> BrandTBLs
		{
			get
			{
				return this.GetTable<BrandTBL>();
			}
		}
		
		public System.Data.Linq.Table<UnloadReport> UnloadReports
		{
			get
			{
				return this.GetTable<UnloadReport>();
			}
		}
		
		public System.Data.Linq.Table<CustomerTBL> CustomerTBLs
		{
			get
			{
				return this.GetTable<CustomerTBL>();
			}
		}
		
		public System.Data.Linq.Table<DetailsTBL> DetailsTBLs
		{
			get
			{
				return this.GetTable<DetailsTBL>();
			}
		}
		
		public System.Data.Linq.Table<GenderTBL> GenderTBLs
		{
			get
			{
				return this.GetTable<GenderTBL>();
			}
		}
		
		public System.Data.Linq.Table<HostTBL> HostTBLs
		{
			get
			{
				return this.GetTable<HostTBL>();
			}
		}
		
		public System.Data.Linq.Table<KalaListTBL> KalaListTBLs
		{
			get
			{
				return this.GetTable<KalaListTBL>();
			}
		}
		
		public System.Data.Linq.Table<KalaTBL> KalaTBLs
		{
			get
			{
				return this.GetTable<KalaTBL>();
			}
		}
		
		public System.Data.Linq.Table<MessageTBL> MessageTBLs
		{
			get
			{
				return this.GetTable<MessageTBL>();
			}
		}
		
		public System.Data.Linq.Table<OperaionsTBL> OperaionsTBLs
		{
			get
			{
				return this.GetTable<OperaionsTBL>();
			}
		}
		
		public System.Data.Linq.Table<orderedKalaTBL> orderedKalaTBLs
		{
			get
			{
				return this.GetTable<orderedKalaTBL>();
			}
		}
		
		public System.Data.Linq.Table<RackTBL> RackTBLs
		{
			get
			{
				return this.GetTable<RackTBL>();
			}
		}
		
		public System.Data.Linq.Table<ReportTBL> ReportTBLs
		{
			get
			{
				return this.GetTable<ReportTBL>();
			}
		}
		
		public System.Data.Linq.Table<SetupTBL> SetupTBLs
		{
			get
			{
				return this.GetTable<SetupTBL>();
			}
		}
		
		public System.Data.Linq.Table<triggerTBL> triggerTBLs
		{
			get
			{
				return this.GetTable<triggerTBL>();
			}
		}
		
		public System.Data.Linq.Table<UsersTBL> UsersTBLs
		{
			get
			{
				return this.GetTable<UsersTBL>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BrandTBL")]
	public partial class BrandTBL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Title;
		
		private string _prefix;
		
		private int _RackID;
		
		private int _fromCell;
		
		private int _toCell;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnprefixChanging(string value);
    partial void OnprefixChanged();
    partial void OnRackIDChanging(int value);
    partial void OnRackIDChanged();
    partial void OnfromCellChanging(int value);
    partial void OnfromCellChanged();
    partial void OntoCellChanging(int value);
    partial void OntoCellChanged();
    #endregion
		
		public BrandTBL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prefix", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string prefix
		{
			get
			{
				return this._prefix;
			}
			set
			{
				if ((this._prefix != value))
				{
					this.OnprefixChanging(value);
					this.SendPropertyChanging();
					this._prefix = value;
					this.SendPropertyChanged("prefix");
					this.OnprefixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RackID", DbType="Int NOT NULL")]
		public int RackID
		{
			get
			{
				return this._RackID;
			}
			set
			{
				if ((this._RackID != value))
				{
					this.OnRackIDChanging(value);
					this.SendPropertyChanging();
					this._RackID = value;
					this.SendPropertyChanged("RackID");
					this.OnRackIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fromCell", DbType="Int NOT NULL")]
		public int fromCell
		{
			get
			{
				return this._fromCell;
			}
			set
			{
				if ((this._fromCell != value))
				{
					this.OnfromCellChanging(value);
					this.SendPropertyChanging();
					this._fromCell = value;
					this.SendPropertyChanged("fromCell");
					this.OnfromCellChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_toCell", DbType="Int NOT NULL")]
		public int toCell
		{
			get
			{
				return this._toCell;
			}
			set
			{
				if ((this._toCell != value))
				{
					this.OntoCellChanging(value);
					this.SendPropertyChanging();
					this._toCell = value;
					this.SendPropertyChanged("toCell");
					this.OntoCellChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UnloadReport")]
	public partial class UnloadReport : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _codeKala;
		
		private string _brandText;
		
		private string _model;
		
		private string _operator;
		
		private string _date;
		
		private string _time;
		
		private string _cells;
		
		private string _rack;
		
		private string _why;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncodeKalaChanging(string value);
    partial void OncodeKalaChanged();
    partial void OnbrandTextChanging(string value);
    partial void OnbrandTextChanged();
    partial void OnmodelChanging(string value);
    partial void OnmodelChanged();
    partial void OnoperatorChanging(string value);
    partial void OnoperatorChanged();
    partial void OndateChanging(string value);
    partial void OndateChanged();
    partial void OntimeChanging(string value);
    partial void OntimeChanged();
    partial void OncellsChanging(string value);
    partial void OncellsChanged();
    partial void OnrackChanging(string value);
    partial void OnrackChanged();
    partial void OnwhyChanging(string value);
    partial void OnwhyChanged();
    #endregion
		
		public UnloadReport()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codeKala", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string codeKala
		{
			get
			{
				return this._codeKala;
			}
			set
			{
				if ((this._codeKala != value))
				{
					this.OncodeKalaChanging(value);
					this.SendPropertyChanging();
					this._codeKala = value;
					this.SendPropertyChanged("codeKala");
					this.OncodeKalaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brandText", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string brandText
		{
			get
			{
				return this._brandText;
			}
			set
			{
				if ((this._brandText != value))
				{
					this.OnbrandTextChanging(value);
					this.SendPropertyChanging();
					this._brandText = value;
					this.SendPropertyChanged("brandText");
					this.OnbrandTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model", DbType="NVarChar(50)")]
		public string model
		{
			get
			{
				return this._model;
			}
			set
			{
				if ((this._model != value))
				{
					this.OnmodelChanging(value);
					this.SendPropertyChanging();
					this._model = value;
					this.SendPropertyChanged("model");
					this.OnmodelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="operator", Storage="_operator", DbType="NVarChar(50)")]
		public string @operator
		{
			get
			{
				return this._operator;
			}
			set
			{
				if ((this._operator != value))
				{
					this.OnoperatorChanging(value);
					this.SendPropertyChanging();
					this._operator = value;
					this.SendPropertyChanged("@operator");
					this.OnoperatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this.OntimeChanging(value);
					this.SendPropertyChanging();
					this._time = value;
					this.SendPropertyChanged("time");
					this.OntimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cells", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string cells
		{
			get
			{
				return this._cells;
			}
			set
			{
				if ((this._cells != value))
				{
					this.OncellsChanging(value);
					this.SendPropertyChanging();
					this._cells = value;
					this.SendPropertyChanged("cells");
					this.OncellsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rack", DbType="NVarChar(50)")]
		public string rack
		{
			get
			{
				return this._rack;
			}
			set
			{
				if ((this._rack != value))
				{
					this.OnrackChanging(value);
					this.SendPropertyChanging();
					this._rack = value;
					this.SendPropertyChanged("rack");
					this.OnrackChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_why", DbType="NVarChar(50)")]
		public string why
		{
			get
			{
				return this._why;
			}
			set
			{
				if ((this._why != value))
				{
					this.OnwhyChanging(value);
					this.SendPropertyChanging();
					this._why = value;
					this.SendPropertyChanged("why");
					this.OnwhyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CustomerTBL")]
	public partial class CustomerTBL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _username;
		
		private string _password;
		
		private string _fullname;
		
		private string _address;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnfullnameChanging(string value);
    partial void OnfullnameChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    #endregion
		
		public CustomerTBL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this.OnfullnameChanging(value);
					this.SendPropertyChanging();
					this._fullname = value;
					this.SendPropertyChanged("fullname");
					this.OnfullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DetailsTBL")]
	public partial class DetailsTBL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _kalaid;
		
		private int _ax;
		
		private string _color;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnkalaidChanging(int value);
    partial void OnkalaidChanged();
    partial void OnaxChanging(int value);
    partial void OnaxChanged();
    partial void OncolorChanging(string value);
    partial void OncolorChanged();
    #endregion
		
		public DetailsTBL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kalaid", DbType="Int NOT NULL")]
		public int kalaid
		{
			get
			{
				return this._kalaid;
			}
			set
			{
				if ((this._kalaid != value))
				{
					this.OnkalaidChanging(value);
					this.SendPropertyChanging();
					this._kalaid = value;
					this.SendPropertyChanged("kalaid");
					this.OnkalaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ax", DbType="Int NOT NULL")]
		public int ax
		{
			get
			{
				return this._ax;
			}
			set
			{
				if ((this._ax != value))
				{
					this.OnaxChanging(value);
					this.SendPropertyChanging();
					this._ax = value;
					this.SendPropertyChanged("ax");
					this.OnaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string color
		{
			get
			{
				return this._color;
			}
			set
			{
				if ((this._color != value))
				{
					this.OncolorChanging(value);
					this.SendPropertyChanging();
					this._color = value;
					this.SendPropertyChanged("color");
					this.OncolorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GenderTBL")]
	public partial class GenderTBL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Title;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    #endregion
		
		public GenderTBL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HostTBL")]
	public partial class HostTBL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _hostname;
		
		private string _hostType;
		
		private bool _stat;
		
		private string _ipAddress;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnhostnameChanging(string value);
    partial void OnhostnameChanged();
    partial void OnhostTypeChanging(string value);
    partial void OnhostTypeChanged();
    partial void OnstatChanging(bool value);
    partial void OnstatChanged();
    partial void OnipAddressChanging(string value);
    partial void OnipAddressChanged();
    #endregion
		
		public HostTBL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hostname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hostname
		{
			get
			{
				return this._hostname;
			}
			set
			{
				if ((this._hostname != value))
				{
					this.OnhostnameChanging(value);
					this.SendPropertyChanging();
					this._hostname = value;
					this.SendPropertyChanged("hostname");
					this.OnhostnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hostType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hostType
		{
			get
			{
				return this._hostType;
			}
			set
			{
				if ((this._hostType != value))
				{
					this.OnhostTypeChanging(value);
					this.SendPropertyChanging();
					this._hostType = value;
					this.SendPropertyChanged("hostType");
					this.OnhostTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stat", DbType="Bit NOT NULL")]
		public bool stat
		{
			get
			{
				return this._stat;
			}
			set
			{
				if ((this._stat != value))
				{
					this.OnstatChanging(value);
					this.SendPropertyChanging();
					this._stat = value;
					this.SendPropertyChanged("stat");
					this.OnstatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ipAddress", DbType="NVarChar(50)")]
		public string ipAddress
		{
			get
			{
				return this._ipAddress;
			}
			set
			{
				if ((this._ipAddress != value))
				{
					this.OnipAddressChanging(value);
					this.SendPropertyChanging();
					this._ipAddress = value;
					this.SendPropertyChanged("ipAddress");
					this.OnipAddressChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KalaListTBL")]
	public partial class KalaListTBL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _kalaid;
		
		private int _userAdd;
		
		private string _barcode;
		
		private string _date;
		
		private string _time;
		
		private int _cell;
		
		private bool _carton;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnkalaidChanging(int value);
    partial void OnkalaidChanged();
    partial void OnuserAddChanging(int value);
    partial void OnuserAddChanged();
    partial void OnbarcodeChanging(string value);
    partial void OnbarcodeChanged();
    partial void OndateChanging(string value);
    partial void OndateChanged();
    partial void OntimeChanging(string value);
    partial void OntimeChanged();
    partial void OncellChanging(int value);
    partial void OncellChanged();
    partial void OncartonChanging(bool value);
    partial void OncartonChanged();
    #endregion
		
		public KalaListTBL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kalaid", DbType="Int NOT NULL")]
		public int kalaid
		{
			get
			{
				return this._kalaid;
			}
			set
			{
				if ((this._kalaid != value))
				{
					this.OnkalaidChanging(value);
					this.SendPropertyChanging();
					this._kalaid = value;
					this.SendPropertyChanged("kalaid");
					this.OnkalaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userAdd", DbType="Int NOT NULL")]
		public int userAdd
		{
			get
			{
				return this._userAdd;
			}
			set
			{
				if ((this._userAdd != value))
				{
					this.OnuserAddChanging(value);
					this.SendPropertyChanging();
					this._userAdd = value;
					this.SendPropertyChanged("userAdd");
					this.OnuserAddChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_barcode", DbType="NVarChar(50)")]
		public string barcode
		{
			get
			{
				return this._barcode;
			}
			set
			{
				if ((this._barcode != value))
				{
					this.OnbarcodeChanging(value);
					this.SendPropertyChanging();
					this._barcode = value;
					this.SendPropertyChanged("barcode");
					this.OnbarcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this.OntimeChanging(value);
					this.SendPropertyChanging();
					this._time = value;
					this.SendPropertyChanged("time");
					this.OntimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell", DbType="Int NOT NULL")]
		public int cell
		{
			get
			{
				return this._cell;
			}
			set
			{
				if ((this._cell != value))
				{
					this.OncellChanging(value);
					this.SendPropertyChanging();
					this._cell = value;
					this.SendPropertyChanged("cell");
					this.OncellChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carton", DbType="Bit NOT NULL")]
		public bool carton
		{
			get
			{
				return this._carton;
			}
			set
			{
				if ((this._carton != value))
				{
					this.OncartonChanging(value);
					this.SendPropertyChanging();
					this._carton = value;
					this.SendPropertyChanged("carton");
					this.OncartonChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KalaTBL")]
	public partial class KalaTBL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _codeKala;
		
		private int _brand;
		
		private string _model;
		
		private string _tag;
		
		private int _gender;
		
		private int _type;
		
		private string _barcode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncodeKalaChanging(int value);
    partial void OncodeKalaChanged();
    partial void OnbrandChanging(int value);
    partial void OnbrandChanged();
    partial void OnmodelChanging(string value);
    partial void OnmodelChanged();
    partial void OntagChanging(string value);
    partial void OntagChanged();
    partial void OngenderChanging(int value);
    partial void OngenderChanged();
    partial void OntypeChanging(int value);
    partial void OntypeChanged();
    partial void OnbarcodeChanging(string value);
    partial void OnbarcodeChanged();
    #endregion
		
		public KalaTBL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codeKala", DbType="Int NOT NULL")]
		public int codeKala
		{
			get
			{
				return this._codeKala;
			}
			set
			{
				if ((this._codeKala != value))
				{
					this.OncodeKalaChanging(value);
					this.SendPropertyChanging();
					this._codeKala = value;
					this.SendPropertyChanged("codeKala");
					this.OncodeKalaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brand", DbType="Int NOT NULL")]
		public int brand
		{
			get
			{
				return this._brand;
			}
			set
			{
				if ((this._brand != value))
				{
					this.OnbrandChanging(value);
					this.SendPropertyChanging();
					this._brand = value;
					this.SendPropertyChanged("brand");
					this.OnbrandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string model
		{
			get
			{
				return this._model;
			}
			set
			{
				if ((this._model != value))
				{
					this.OnmodelChanging(value);
					this.SendPropertyChanging();
					this._model = value;
					this.SendPropertyChanged("model");
					this.OnmodelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string tag
		{
			get
			{
				return this._tag;
			}
			set
			{
				if ((this._tag != value))
				{
					this.OntagChanging(value);
					this.SendPropertyChanging();
					this._tag = value;
					this.SendPropertyChanged("tag");
					this.OntagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="Int NOT NULL")]
		public int gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int NOT NULL")]
		public int type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_barcode", DbType="NVarChar(50)")]
		public string barcode
		{
			get
			{
				return this._barcode;
			}
			set
			{
				if ((this._barcode != value))
				{
					this.OnbarcodeChanging(value);
					this.SendPropertyChanging();
					this._barcode = value;
					this.SendPropertyChanged("barcode");
					this.OnbarcodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MessageTBL")]
	public partial class MessageTBL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _type;
		
		private string _title;
		
		private System.Nullable<bool> _read;
		
		private System.Nullable<bool> _archive;
		
		private System.Nullable<int> _docoutid;
		
		private string _timestamp;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnreadChanging(System.Nullable<bool> value);
    partial void OnreadChanged();
    partial void OnarchiveChanging(System.Nullable<bool> value);
    partial void OnarchiveChanged();
    partial void OndocoutidChanging(System.Nullable<int> value);
    partial void OndocoutidChanged();
    partial void OntimestampChanging(string value);
    partial void OntimestampChanged();
    #endregion
		
		public MessageTBL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(100)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(500)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[read]", Storage="_read", DbType="Bit")]
		public System.Nullable<bool> read
		{
			get
			{
				return this._read;
			}
			set
			{
				if ((this._read != value))
				{
					this.OnreadChanging(value);
					this.SendPropertyChanging();
					this._read = value;
					this.SendPropertyChanged("read");
					this.OnreadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_archive", DbType="Bit")]
		public System.Nullable<bool> archive
		{
			get
			{
				return this._archive;
			}
			set
			{
				if ((this._archive != value))
				{
					this.OnarchiveChanging(value);
					this.SendPropertyChanging();
					this._archive = value;
					this.SendPropertyChanged("archive");
					this.OnarchiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_docoutid", DbType="Int")]
		public System.Nullable<int> docoutid
		{
			get
			{
				return this._docoutid;
			}
			set
			{
				if ((this._docoutid != value))
				{
					this.OndocoutidChanging(value);
					this.SendPropertyChanging();
					this._docoutid = value;
					this.SendPropertyChanged("docoutid");
					this.OndocoutidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timestamp", DbType="NVarChar(100)")]
		public string timestamp
		{
			get
			{
				return this._timestamp;
			}
			set
			{
				if ((this._timestamp != value))
				{
					this.OntimestampChanging(value);
					this.SendPropertyChanging();
					this._timestamp = value;
					this.SendPropertyChanged("timestamp");
					this.OntimestampChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OperaionsTBL")]
	public partial class OperaionsTBL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _title;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    #endregion
		
		public OperaionsTBL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.orderedKalaTBL")]
	public partial class orderedKalaTBL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _kalaid;
		
		private string _date;
		
		private string _time;
		
		private string _fullname;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnkalaidChanging(int value);
    partial void OnkalaidChanged();
    partial void OndateChanging(string value);
    partial void OndateChanged();
    partial void OntimeChanging(string value);
    partial void OntimeChanged();
    partial void OnfullnameChanging(string value);
    partial void OnfullnameChanged();
    #endregion
		
		public orderedKalaTBL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kalaid", DbType="Int NOT NULL")]
		public int kalaid
		{
			get
			{
				return this._kalaid;
			}
			set
			{
				if ((this._kalaid != value))
				{
					this.OnkalaidChanging(value);
					this.SendPropertyChanging();
					this._kalaid = value;
					this.SendPropertyChanged("kalaid");
					this.OnkalaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this.OntimeChanging(value);
					this.SendPropertyChanging();
					this._time = value;
					this.SendPropertyChanged("time");
					this.OntimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this.OnfullnameChanging(value);
					this.SendPropertyChanging();
					this._fullname = value;
					this.SendPropertyChanged("fullname");
					this.OnfullnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RackTBL")]
	public partial class RackTBL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _x;
		
		private int _y;
		
		private int _max;
		
		private string _tag;
		
		private double _atf;
		
		private int _type;
		
		private string _ip;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnxChanging(int value);
    partial void OnxChanged();
    partial void OnyChanging(int value);
    partial void OnyChanged();
    partial void OnmaxChanging(int value);
    partial void OnmaxChanged();
    partial void OntagChanging(string value);
    partial void OntagChanged();
    partial void OnatfChanging(double value);
    partial void OnatfChanged();
    partial void OntypeChanging(int value);
    partial void OntypeChanged();
    partial void OnipChanging(string value);
    partial void OnipChanged();
    #endregion
		
		public RackTBL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_x", DbType="Int NOT NULL")]
		public int x
		{
			get
			{
				return this._x;
			}
			set
			{
				if ((this._x != value))
				{
					this.OnxChanging(value);
					this.SendPropertyChanging();
					this._x = value;
					this.SendPropertyChanged("x");
					this.OnxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_y", DbType="Int NOT NULL")]
		public int y
		{
			get
			{
				return this._y;
			}
			set
			{
				if ((this._y != value))
				{
					this.OnyChanging(value);
					this.SendPropertyChanging();
					this._y = value;
					this.SendPropertyChanged("y");
					this.OnyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_max", DbType="Int NOT NULL")]
		public int max
		{
			get
			{
				return this._max;
			}
			set
			{
				if ((this._max != value))
				{
					this.OnmaxChanging(value);
					this.SendPropertyChanging();
					this._max = value;
					this.SendPropertyChanged("max");
					this.OnmaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string tag
		{
			get
			{
				return this._tag;
			}
			set
			{
				if ((this._tag != value))
				{
					this.OntagChanging(value);
					this.SendPropertyChanging();
					this._tag = value;
					this.SendPropertyChanged("tag");
					this.OntagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_atf", DbType="Float NOT NULL")]
		public double atf
		{
			get
			{
				return this._atf;
			}
			set
			{
				if ((this._atf != value))
				{
					this.OnatfChanging(value);
					this.SendPropertyChanging();
					this._atf = value;
					this.SendPropertyChanged("atf");
					this.OnatfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int NOT NULL")]
		public int type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip", DbType="NVarChar(50)")]
		public string ip
		{
			get
			{
				return this._ip;
			}
			set
			{
				if ((this._ip != value))
				{
					this.OnipChanging(value);
					this.SendPropertyChanging();
					this._ip = value;
					this.SendPropertyChanged("ip");
					this.OnipChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReportTBL")]
	public partial class ReportTBL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _docid;
		
		private string _date;
		
		private string _time;
		
		private int _userid;
		
		private int _operation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndocidChanging(int value);
    partial void OndocidChanged();
    partial void OndateChanging(string value);
    partial void OndateChanged();
    partial void OntimeChanging(string value);
    partial void OntimeChanged();
    partial void OnuseridChanging(int value);
    partial void OnuseridChanged();
    partial void OnoperationChanging(int value);
    partial void OnoperationChanged();
    #endregion
		
		public ReportTBL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_docid", DbType="Int NOT NULL")]
		public int docid
		{
			get
			{
				return this._docid;
			}
			set
			{
				if ((this._docid != value))
				{
					this.OndocidChanging(value);
					this.SendPropertyChanging();
					this._docid = value;
					this.SendPropertyChanged("docid");
					this.OndocidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this.OntimeChanging(value);
					this.SendPropertyChanging();
					this._time = value;
					this.SendPropertyChanged("time");
					this.OntimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int NOT NULL")]
		public int userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operation", DbType="Int NOT NULL")]
		public int operation
		{
			get
			{
				return this._operation;
			}
			set
			{
				if ((this._operation != value))
				{
					this.OnoperationChanging(value);
					this.SendPropertyChanging();
					this._operation = value;
					this.SendPropertyChanged("operation");
					this.OnoperationChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SetupTBL")]
	public partial class SetupTBL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _programName;
		
		private string _version;
		
		private string _tag;
		
		private System.Nullable<int> _gridCount;
		
		private string _port;
		
		private string _sterategy;
		
		private System.Nullable<bool> _manualCellSet;
		
		private string _securityType;
		
		private System.Nullable<int> _tempMax;
		
		private string _startTime;
		
		private string _endTime;
		
		private System.Nullable<int> _readMaxTime;
		
		private System.Nullable<bool> _thursday;
		
		private string _programWorkingPath;
		
		private System.Nullable<int> _smslogin;
		
		private System.Nullable<bool> _smsTemp;
		
		private System.Nullable<bool> _smsRack90;
		
		private System.Nullable<bool> _regNameFP;
		
		private string _SSFConsoleIP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnprogramNameChanging(string value);
    partial void OnprogramNameChanged();
    partial void OnversionChanging(string value);
    partial void OnversionChanged();
    partial void OntagChanging(string value);
    partial void OntagChanged();
    partial void OngridCountChanging(System.Nullable<int> value);
    partial void OngridCountChanged();
    partial void OnportChanging(string value);
    partial void OnportChanged();
    partial void OnsterategyChanging(string value);
    partial void OnsterategyChanged();
    partial void OnmanualCellSetChanging(System.Nullable<bool> value);
    partial void OnmanualCellSetChanged();
    partial void OnsecurityTypeChanging(string value);
    partial void OnsecurityTypeChanged();
    partial void OntempMaxChanging(System.Nullable<int> value);
    partial void OntempMaxChanged();
    partial void OnstartTimeChanging(string value);
    partial void OnstartTimeChanged();
    partial void OnendTimeChanging(string value);
    partial void OnendTimeChanged();
    partial void OnreadMaxTimeChanging(System.Nullable<int> value);
    partial void OnreadMaxTimeChanged();
    partial void OnthursdayChanging(System.Nullable<bool> value);
    partial void OnthursdayChanged();
    partial void OnprogramWorkingPathChanging(string value);
    partial void OnprogramWorkingPathChanged();
    partial void OnsmsloginChanging(System.Nullable<int> value);
    partial void OnsmsloginChanged();
    partial void OnsmsTempChanging(System.Nullable<bool> value);
    partial void OnsmsTempChanged();
    partial void OnsmsRack90Changing(System.Nullable<bool> value);
    partial void OnsmsRack90Changed();
    partial void OnregNameFPChanging(System.Nullable<bool> value);
    partial void OnregNameFPChanged();
    partial void OnSSFConsoleIPChanging(string value);
    partial void OnSSFConsoleIPChanged();
    #endregion
		
		public SetupTBL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_programName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string programName
		{
			get
			{
				return this._programName;
			}
			set
			{
				if ((this._programName != value))
				{
					this.OnprogramNameChanging(value);
					this.SendPropertyChanging();
					this._programName = value;
					this.SendPropertyChanged("programName");
					this.OnprogramNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_version", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string version
		{
			get
			{
				return this._version;
			}
			set
			{
				if ((this._version != value))
				{
					this.OnversionChanging(value);
					this.SendPropertyChanging();
					this._version = value;
					this.SendPropertyChanged("version");
					this.OnversionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag", DbType="NVarChar(1000)")]
		public string tag
		{
			get
			{
				return this._tag;
			}
			set
			{
				if ((this._tag != value))
				{
					this.OntagChanging(value);
					this.SendPropertyChanging();
					this._tag = value;
					this.SendPropertyChanged("tag");
					this.OntagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gridCount", DbType="Int")]
		public System.Nullable<int> gridCount
		{
			get
			{
				return this._gridCount;
			}
			set
			{
				if ((this._gridCount != value))
				{
					this.OngridCountChanging(value);
					this.SendPropertyChanging();
					this._gridCount = value;
					this.SendPropertyChanged("gridCount");
					this.OngridCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_port", DbType="NVarChar(100)")]
		public string port
		{
			get
			{
				return this._port;
			}
			set
			{
				if ((this._port != value))
				{
					this.OnportChanging(value);
					this.SendPropertyChanging();
					this._port = value;
					this.SendPropertyChanged("port");
					this.OnportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sterategy", DbType="NVarChar(50)")]
		public string sterategy
		{
			get
			{
				return this._sterategy;
			}
			set
			{
				if ((this._sterategy != value))
				{
					this.OnsterategyChanging(value);
					this.SendPropertyChanging();
					this._sterategy = value;
					this.SendPropertyChanged("sterategy");
					this.OnsterategyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manualCellSet", DbType="Bit")]
		public System.Nullable<bool> manualCellSet
		{
			get
			{
				return this._manualCellSet;
			}
			set
			{
				if ((this._manualCellSet != value))
				{
					this.OnmanualCellSetChanging(value);
					this.SendPropertyChanging();
					this._manualCellSet = value;
					this.SendPropertyChanged("manualCellSet");
					this.OnmanualCellSetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_securityType", DbType="NVarChar(50)")]
		public string securityType
		{
			get
			{
				return this._securityType;
			}
			set
			{
				if ((this._securityType != value))
				{
					this.OnsecurityTypeChanging(value);
					this.SendPropertyChanging();
					this._securityType = value;
					this.SendPropertyChanged("securityType");
					this.OnsecurityTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tempMax", DbType="Int")]
		public System.Nullable<int> tempMax
		{
			get
			{
				return this._tempMax;
			}
			set
			{
				if ((this._tempMax != value))
				{
					this.OntempMaxChanging(value);
					this.SendPropertyChanging();
					this._tempMax = value;
					this.SendPropertyChanged("tempMax");
					this.OntempMaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startTime", DbType="NVarChar(50)")]
		public string startTime
		{
			get
			{
				return this._startTime;
			}
			set
			{
				if ((this._startTime != value))
				{
					this.OnstartTimeChanging(value);
					this.SendPropertyChanging();
					this._startTime = value;
					this.SendPropertyChanged("startTime");
					this.OnstartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endTime", DbType="NVarChar(50)")]
		public string endTime
		{
			get
			{
				return this._endTime;
			}
			set
			{
				if ((this._endTime != value))
				{
					this.OnendTimeChanging(value);
					this.SendPropertyChanging();
					this._endTime = value;
					this.SendPropertyChanged("endTime");
					this.OnendTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_readMaxTime", DbType="Int")]
		public System.Nullable<int> readMaxTime
		{
			get
			{
				return this._readMaxTime;
			}
			set
			{
				if ((this._readMaxTime != value))
				{
					this.OnreadMaxTimeChanging(value);
					this.SendPropertyChanging();
					this._readMaxTime = value;
					this.SendPropertyChanged("readMaxTime");
					this.OnreadMaxTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thursday", DbType="Bit")]
		public System.Nullable<bool> thursday
		{
			get
			{
				return this._thursday;
			}
			set
			{
				if ((this._thursday != value))
				{
					this.OnthursdayChanging(value);
					this.SendPropertyChanging();
					this._thursday = value;
					this.SendPropertyChanged("thursday");
					this.OnthursdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_programWorkingPath", DbType="NVarChar(500)")]
		public string programWorkingPath
		{
			get
			{
				return this._programWorkingPath;
			}
			set
			{
				if ((this._programWorkingPath != value))
				{
					this.OnprogramWorkingPathChanging(value);
					this.SendPropertyChanging();
					this._programWorkingPath = value;
					this.SendPropertyChanged("programWorkingPath");
					this.OnprogramWorkingPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_smslogin", DbType="Int")]
		public System.Nullable<int> smslogin
		{
			get
			{
				return this._smslogin;
			}
			set
			{
				if ((this._smslogin != value))
				{
					this.OnsmsloginChanging(value);
					this.SendPropertyChanging();
					this._smslogin = value;
					this.SendPropertyChanged("smslogin");
					this.OnsmsloginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_smsTemp", DbType="Bit")]
		public System.Nullable<bool> smsTemp
		{
			get
			{
				return this._smsTemp;
			}
			set
			{
				if ((this._smsTemp != value))
				{
					this.OnsmsTempChanging(value);
					this.SendPropertyChanging();
					this._smsTemp = value;
					this.SendPropertyChanged("smsTemp");
					this.OnsmsTempChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_smsRack90", DbType="Bit")]
		public System.Nullable<bool> smsRack90
		{
			get
			{
				return this._smsRack90;
			}
			set
			{
				if ((this._smsRack90 != value))
				{
					this.OnsmsRack90Changing(value);
					this.SendPropertyChanging();
					this._smsRack90 = value;
					this.SendPropertyChanged("smsRack90");
					this.OnsmsRack90Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_regNameFP", DbType="Bit")]
		public System.Nullable<bool> regNameFP
		{
			get
			{
				return this._regNameFP;
			}
			set
			{
				if ((this._regNameFP != value))
				{
					this.OnregNameFPChanging(value);
					this.SendPropertyChanging();
					this._regNameFP = value;
					this.SendPropertyChanged("regNameFP");
					this.OnregNameFPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSFConsoleIP", DbType="NVarChar(50)")]
		public string SSFConsoleIP
		{
			get
			{
				return this._SSFConsoleIP;
			}
			set
			{
				if ((this._SSFConsoleIP != value))
				{
					this.OnSSFConsoleIPChanging(value);
					this.SendPropertyChanging();
					this._SSFConsoleIP = value;
					this.SendPropertyChanged("SSFConsoleIP");
					this.OnSSFConsoleIPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.triggerTBL")]
	public partial class triggerTBL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _ttr;
		
		private System.Nullable<int> _hostID;
		
		private System.Nullable<bool> _forceExit;
		
		private System.Nullable<int> _uid;
		
		private string _message;
		
		private string _host;
		
		private string _senderHost;
		
		private System.Nullable<bool> _reqTrig;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnttrChanging(int value);
    partial void OnttrChanged();
    partial void OnhostIDChanging(System.Nullable<int> value);
    partial void OnhostIDChanged();
    partial void OnforceExitChanging(System.Nullable<bool> value);
    partial void OnforceExitChanged();
    partial void OnuidChanging(System.Nullable<int> value);
    partial void OnuidChanged();
    partial void OnmessageChanging(string value);
    partial void OnmessageChanged();
    partial void OnhostChanging(string value);
    partial void OnhostChanged();
    partial void OnsenderHostChanging(string value);
    partial void OnsenderHostChanged();
    partial void OnreqTrigChanging(System.Nullable<bool> value);
    partial void OnreqTrigChanged();
    #endregion
		
		public triggerTBL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ttr", DbType="Int NOT NULL")]
		public int ttr
		{
			get
			{
				return this._ttr;
			}
			set
			{
				if ((this._ttr != value))
				{
					this.OnttrChanging(value);
					this.SendPropertyChanging();
					this._ttr = value;
					this.SendPropertyChanged("ttr");
					this.OnttrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hostID", DbType="Int")]
		public System.Nullable<int> hostID
		{
			get
			{
				return this._hostID;
			}
			set
			{
				if ((this._hostID != value))
				{
					this.OnhostIDChanging(value);
					this.SendPropertyChanging();
					this._hostID = value;
					this.SendPropertyChanged("hostID");
					this.OnhostIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_forceExit", DbType="Bit")]
		public System.Nullable<bool> forceExit
		{
			get
			{
				return this._forceExit;
			}
			set
			{
				if ((this._forceExit != value))
				{
					this.OnforceExitChanging(value);
					this.SendPropertyChanging();
					this._forceExit = value;
					this.SendPropertyChanged("forceExit");
					this.OnforceExitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", DbType="Int")]
		public System.Nullable<int> uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_message", DbType="NVarChar(500)")]
		public string message
		{
			get
			{
				return this._message;
			}
			set
			{
				if ((this._message != value))
				{
					this.OnmessageChanging(value);
					this.SendPropertyChanging();
					this._message = value;
					this.SendPropertyChanged("message");
					this.OnmessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_host", DbType="NVarChar(50)")]
		public string host
		{
			get
			{
				return this._host;
			}
			set
			{
				if ((this._host != value))
				{
					this.OnhostChanging(value);
					this.SendPropertyChanging();
					this._host = value;
					this.SendPropertyChanged("host");
					this.OnhostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senderHost", DbType="NVarChar(50)")]
		public string senderHost
		{
			get
			{
				return this._senderHost;
			}
			set
			{
				if ((this._senderHost != value))
				{
					this.OnsenderHostChanging(value);
					this.SendPropertyChanging();
					this._senderHost = value;
					this.SendPropertyChanged("senderHost");
					this.OnsenderHostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reqTrig", DbType="Bit")]
		public System.Nullable<bool> reqTrig
		{
			get
			{
				return this._reqTrig;
			}
			set
			{
				if ((this._reqTrig != value))
				{
					this.OnreqTrigChanging(value);
					this.SendPropertyChanging();
					this._reqTrig = value;
					this.SendPropertyChanged("reqTrig");
					this.OnreqTrigChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UsersTBL")]
	public partial class UsersTBL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _username;
		
		private string _password;
		
		private string _fullname;
		
		private int _priority;
		
		private string _semat;
		
		private string _lastlogin;
		
		private int _visit;
		
		private string _rfid;
		
		private string _fingerPrint;
		
		private string _mobilenumber;
		
		private string _type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnfullnameChanging(string value);
    partial void OnfullnameChanged();
    partial void OnpriorityChanging(int value);
    partial void OnpriorityChanged();
    partial void OnsematChanging(string value);
    partial void OnsematChanged();
    partial void OnlastloginChanging(string value);
    partial void OnlastloginChanged();
    partial void OnvisitChanging(int value);
    partial void OnvisitChanged();
    partial void OnrfidChanging(string value);
    partial void OnrfidChanged();
    partial void OnfingerPrintChanging(string value);
    partial void OnfingerPrintChanged();
    partial void OnmobilenumberChanging(string value);
    partial void OnmobilenumberChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    #endregion
		
		public UsersTBL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this.OnfullnameChanging(value);
					this.SendPropertyChanging();
					this._fullname = value;
					this.SendPropertyChanged("fullname");
					this.OnfullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priority", DbType="Int NOT NULL")]
		public int priority
		{
			get
			{
				return this._priority;
			}
			set
			{
				if ((this._priority != value))
				{
					this.OnpriorityChanging(value);
					this.SendPropertyChanging();
					this._priority = value;
					this.SendPropertyChanged("priority");
					this.OnpriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_semat", DbType="NVarChar(50)")]
		public string semat
		{
			get
			{
				return this._semat;
			}
			set
			{
				if ((this._semat != value))
				{
					this.OnsematChanging(value);
					this.SendPropertyChanging();
					this._semat = value;
					this.SendPropertyChanged("semat");
					this.OnsematChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastlogin", DbType="NVarChar(50)")]
		public string lastlogin
		{
			get
			{
				return this._lastlogin;
			}
			set
			{
				if ((this._lastlogin != value))
				{
					this.OnlastloginChanging(value);
					this.SendPropertyChanging();
					this._lastlogin = value;
					this.SendPropertyChanged("lastlogin");
					this.OnlastloginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit", DbType="Int NOT NULL")]
		public int visit
		{
			get
			{
				return this._visit;
			}
			set
			{
				if ((this._visit != value))
				{
					this.OnvisitChanging(value);
					this.SendPropertyChanging();
					this._visit = value;
					this.SendPropertyChanged("visit");
					this.OnvisitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rfid", DbType="NVarChar(100)")]
		public string rfid
		{
			get
			{
				return this._rfid;
			}
			set
			{
				if ((this._rfid != value))
				{
					this.OnrfidChanging(value);
					this.SendPropertyChanging();
					this._rfid = value;
					this.SendPropertyChanged("rfid");
					this.OnrfidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fingerPrint", DbType="NVarChar(100)")]
		public string fingerPrint
		{
			get
			{
				return this._fingerPrint;
			}
			set
			{
				if ((this._fingerPrint != value))
				{
					this.OnfingerPrintChanging(value);
					this.SendPropertyChanging();
					this._fingerPrint = value;
					this.SendPropertyChanged("fingerPrint");
					this.OnfingerPrintChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobilenumber", DbType="NVarChar(50)")]
		public string mobilenumber
		{
			get
			{
				return this._mobilenumber;
			}
			set
			{
				if ((this._mobilenumber != value))
				{
					this.OnmobilenumberChanging(value);
					this.SendPropertyChanging();
					this._mobilenumber = value;
					this.SendPropertyChanged("mobilenumber");
					this.OnmobilenumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(50)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
