<?xml version="1.0" encoding="utf-8"?><Database Name="TimeTilcoDB" Class="LinqDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=TILCOSERVERWIN\SQLTIME;Initial Catalog=TimeTilcoDB;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TimeTilcoDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AbsentMainTBL" Member="AbsentMainTBLs">
    <Type Name="AbsentMainTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="staffid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="absentType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tag" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DayofWeek" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UsersTBL" Member="UsersTBLs">
    <Type Name="UsersTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fullname" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="priority" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="semat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lastlogin" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="visit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="rfid" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="fingerPrint" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="mobilenumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AbsentTBL" Member="AbsentTBLs">
    <Type Name="AbsentTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="staffid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="absentType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tag" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DayofWeek" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AbsentTempTBL" Member="AbsentTempTBLs">
    <Type Name="AbsentTempTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="staffid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="absentType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tag" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DayofWeek" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AbsentThisMonthTBL" Member="AbsentThisMonthTBLs">
    <Type Name="AbsentThisMonthTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="staffid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="absentType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tag" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DayofWeek" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AbsentTypeTBL" Member="AbsentTypeTBLs">
    <Type Name="AbsentTypeTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DocOutTBL" Member="DocOutTBLs">
    <Type Name="DocOutTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="docid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="time1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="date2" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="time2" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tag" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="distination" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DocumentsTBL" Member="DocumentsTBLs">
    <Type Name="DocumentsTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="rackid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cell" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="rootid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hasphoto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="userAdd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="archive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="docOut" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="shomareParvande" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nameTarh" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="tarikhPaziresh" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="tarikhRad" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="noeTarh" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="ostan" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="namePishnahadDahande" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="noeIsargari" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="kholaseTarh" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="mizanSamayeLazem" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="vaziatParvandeh" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="noeSherkatTabe" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="tarikhStelem" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="tarikhPasokh" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="elatRad" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="Tahsilat" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="shmareTamas" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="IRR" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="NPV" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="PBP" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="tozihat" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="telephone" Type="System.String" DbType="NVarChar(900) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="eghdamatEjraeiAnjamShode" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="shahrestan" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HelpTBL" Member="HelpTBLs">
    <Type Name="HelpTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="date" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="day" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="month" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HostTBL" Member="HostTBLs">
    <Type Name="HostTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="hostname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="hostType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="stat" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ipAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LogTBL" Member="LogTBLs">
    <Type Name="LogTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="staffid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="time" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="[in]" Member="in" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="saved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DayOfWeek" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MainLogTBL" Member="MainLogTBLs">
    <Type Name="MainLogTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="staffid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="takhir" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ezafekar" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="sumTime" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="tag" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="err" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="timeIn" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="timeOut" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DayofWeek" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MainTempTBL" Member="MainTempTBLs">
    <Type Name="MainTempTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="staffid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="takhir" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ezafekar" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="sumTime" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="tag" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="err" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="timeIn" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="timeOut" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DayofWeek" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MessageTBL" Member="MessageTBLs">
    <Type Name="MessageTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="[read]" Member="read" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="archive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="docoutid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="timestamp" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OperaionsTBL" Member="OperaionsTBLs">
    <Type Name="OperaionsTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PhotosTBL" Member="PhotosTBLs">
    <Type Name="PhotosTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="docid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="tag" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="category" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PresentTBL" Member="PresentTBLs">
    <Type Name="PresentTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="staffid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="time" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.RackTBL" Member="RackTBLs">
    <Type Name="RackTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="x" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="y" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="max" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tag" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="atf" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ReportTBL" Member="ReportTBLs">
    <Type Name="ReportTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="docid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="time" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="operation" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.RequestTBL" Member="RequestTBLs">
    <Type Name="RequestTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="uid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hostname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="docid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.RootTBL" Member="RootTBLs">
    <Type Name="RootTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="tag" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.semiDocout" Member="semiDocouts">
    <Type Name="semiDocout">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="docid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="time" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="archive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="distination" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SetupTBL" Member="SetupTBLs">
    <Type Name="SetupTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="programName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="version" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tag" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="gridCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="port" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="sterategy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="manualCellSet" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="securityType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tempMax" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="startTime" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="endTime" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="readMaxTime" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thursday" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="programWorkingPath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="smslogin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="smsTemp" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="smsRack90" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="regNameFP" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TakhirMax" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="BetweenMax" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="facescannerIP" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="endTimeThu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.StaffTBL" Member="StaffTBLs">
    <Type Name="StaffTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="personel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="family" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="unit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="semat" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="edu" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="mobile" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="dom" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="dob" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="maried" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ThisMonthTBL" Member="ThisMonthTBLs">
    <Type Name="ThisMonthTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="staffid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="takhir" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ezafekar" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="sumTime" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="tag" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="err" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="timeIn" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="timeOut" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DayofWeek" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.triggerTBL" Member="triggerTBLs">
    <Type Name="triggerTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ttr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hostID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="forceExit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="uid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="message" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="host" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="senderHost" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="reqTrig" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TypeTBL" Member="TypeTBLs">
    <Type Name="TypeTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="kindid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UnitTBL" Member="UnitTBLs">
    <Type Name="UnitTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tag" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
</Database>